hmcts/civil-commons

- .github/workflows/jitpack_build.yml
- build.gradle
- jitpack.yml
- src/test/java/uk/gov/hmcts/reform/civil/helpers/LocalDateTimeHelperTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/CategoryServiceTest.java
- src/test/java/uk/gov/hmcts/reform/civil/service/OrganisationServiceTest.java
CIV-7900 - Publish Jar File
Publish Jar File to JitPack
```
[ ] Yes
[ x  ] No
```
> CIV-7900 - Publish Jar File

- build.gradle
- config/owasp/suppressions.xml
> Fix build issues

- .github/workflows/changelog.yml
> Add Release Drafter

- build.gradle
> Add Release

- build.gradle
> Add artifacts

- build.gradle
> Fix publishing script

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/utils/StringUtils.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearing/HearingGetResponse.java
- src/test/java/uk/gov/hmcts/reform/civil/utils/StringUtilsTest.java
https://tools.hmcts.net/jira/browse/CIV-7964
https://tools.hmcts.net/jira/browse/CIV-7980
Transferring changes from service branch for above tickets
```
[ ] Yes
[ ] No
```
> CIV-7980 7964 Generate Hearing Notice

- src/main/resources/application.yml
https://tools.hmcts.net/jira/browse/CIV-9509
> CIV-9509 adding am ROLE_ASSIGNMENT_SERVICE_API_URL

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-7965
- add new templates
```
[ ] Yes
[ ] No
```
> CIV-7965 Add new templates to NotificationsProperties

- build.gradle
- src/main/java/uk/gov/hmcts/reform/civil/config/LaunchDarklyConfiguration.java
upgraded launch darkly and updated the config from deprecated interface to documentation guided replacement
```
[ ] Yes
[ ] No
```
> upgraded launch darkly

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-7989
```
[ ] Yes
[ ] No
```
> CIV-7989 Template for hearing listed defendant hmc

- src/main/java/uk/gov/hmcts/reform/hmc/model/unnotifiedhearings/HearingDay.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/unnotifiedhearings/PartiesNotifiedServiceData.java
https://tools.hmcts.net/jira/browse/CIV-8888
- update service data dates model
```
[ ] Yes
[ ] No
```
> CIV-8888 update parties notified model

- src/main/java/uk/gov/hmcts/reform/civil/documentmanagement/model/DocumentType.java
https://tools.hmcts.net/jira/browse/CIV-9807
added new document type 'Defence Translated Document'.
```
[ ] Yes
[x] No
```
> CIV-9807 - CUI Welsh Translation - Upload Translated Document requires new Document type

- src/main/java/uk/gov/hmcts/reform/civil/documentmanagement/SecuredDocumentManagementService.java
logging {} added from missed off
```
[ ] Yes
[ ] No
```
> updated logging for auth tokens

- src/main/java/uk/gov/hmcts/reform/hmc/client/HearingsApi.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearing/Attendees.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearing/HearingSubChannel.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearings/CaseHearing.java
- src/main/java/uk/gov/hmcts/reform/hmc/model/hearings/HearingsResponse.java
- src/main/java/uk/gov/hmcts/reform/hmc/service/HearingsService.java
- src/test/java/uk/gov/hmcts/reform/hmc/service/HearingsServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-3565
- Added support for calling the get hearings hmc api
```
[ ] Yes
[X] No
```
> CIV-3565 HMC get hearings

- config/owasp/suppressions.xml
N/A
Suppressing False Positive 
```
[ ] Yes
[x] No
```
> Suppress false positive for CVE-2023-34034

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-8322
added new notification property.
```
[ ] Yes
[x] No
```
> CIV-8322 - Update NotificationsProperties.java

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-7951
Added gov.uk Notify email template for generic LiP updates
```
[ ] Yes
[x] No
```
> CIV-9123 - added generic update email template for LiP

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
@ NotEmpty
private String notifyDefendantLIPClaimantSettleTheClaimTemplate;
```
[ ] Yes
[X] No
```
> CIV-7733 Hearing Notice: Send notification to LIP when hearing notice created

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-7846
Added template for when claimant/defendant is LiP.
```
[ ] Yes
[x] No
```
> CIV-7846 - added template for evidence upload LiP notification

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-10125
> CIV-10125 Adding new notification for 1v2 DS Spec

- src/main/java/uk/gov/hmcts/reform/civil/service/BulkPrintService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/BulkPrintServiceTest.java
CIV-0000 Adding recipients in letter service
```
[ ] Yes
[x ] No
```
> CIV-0000 Adding recipients in letter service

- src/main/java/uk/gov/hmcts/reform/civil/documentmanagement/model/DocumentType.java
https://tools.hmcts.net/jira/browse/CIV-8997
add new document type for draft form
```
[ ] Yes
[ ] No
```
> CIV-8997 add new document type

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-9156
add claimant notification template
```
[ ] Yes
[x] No
```
> CIV-9156 Claimant intent claimant notification

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
:### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-6719
Notification--Debt Respite - Submit Function
```
[ ] Yes
[x] No
```
> CIV-6719 added properties for noitification of breathing space entered for lip

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-8998
added new notification property.
```
[ ] Yes
[x] No
```
> CIV-8998 - Claim Submission - Notification where payment is required

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-10686
Added new notification property
```
[ ] Yes
[ ] No
```
> CIV-10686 Added new notification property

- src/main/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleApi.java
- src/test/java/uk/gov/hmcts/reform/civil/launchdarkly/FeatureToggleApiTest.java
https://tools.hmcts.net/jira/browse/CIV-10753
```
[ ] Yes
[X] No
```
> CIV- 8305 Added location whitelisting to feature toggle api

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-10908
new template id added
```
[ ] Yes
[ ] No
```
> added new template property

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-6393
added 2 new properties
```
[ ] Yes
[x] No
```
> CIV- 6393 added new properties

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-10336
- add new templates
```
[ ] Yes
[ ] No
```
> CIV-10336 Add EA notification templates

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
> CIV-10257_10287_CIV-10168 notification added properties

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-11073
add claimant notification template for HWF
```
[ ] Yes
[x] No
```
> CIV-11073 add claimant notification template for HWF

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-8241
Set Up Variable for new template
```
[ ] Yes
[ ] No
```
> CIV-8241 Create Notifications Variable

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-8169
Sign settlement agreement submit function notifications
```
[ ] Yes
[x] No
```
> CIV-8169 sign settlement agreement submit function notifications

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-8791
```
[ ] Yes
[x] No
```
> CIV-8791 new notification template name

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-11209
Adding new template
```
[ ] Yes
[ x ] No
```
> feat/CIV-11209 Add notifyClaimantLipHelpWithFees template

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
…on notification
```
[ ] Yes
[ ] No
```
> CIV-12265 Added Notification property for claimant lip claim submission

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12315
https://tools.hmcts.net/jira/browse/CIV-12288
Added 2 properties for ClaimantLip to send a notification during lip v lip claim submission.
```
[ ] Yes
[x] No
```
> CIV - 0000 - Update NotificationsProperties.java

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12364
Added new notification property  to notify Claimant LiP about Claim Update.
```
[ ] Yes
[x] No
```
> CIV-12364 - Update NotificationsProperties.java

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12281
Add bilingual notification template, plus change from CIV-11543.
```
[ ] Yes
[x] No
```
> CIV-12281 claimant intention translated doc notifications

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12316
```
[ ] Yes
[ ] No
```
> CIV-12316 Translate settlement agreement notification

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12577
```
[ ] Yes
[x] No
```
> CIV-12577 More information required HwF - Claimant notifications

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-12552
```
[ ] Yes
[X] No
```
> CIV-12552 : No Remission template

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
[Email notifications: Claimant/Defendant LR - Judgment varied following Determination of Means](https://tools.hmcts.net/jira/browse/CIV-13171)
These notifications are generated following the editing of a Judgment by a caseworker after a determination of means
```
[ ] Yes
[X] No
```
> CIV-13171 Notify Judgment varied following Determination of Means

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13109
Added property for Set Aside Judgement Notification
```
[ ] Yes
[ ] No
```
> CIV-13109: Added property for Set Aside Judgment Notification

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
Reverts hmcts/civil-commons#130
> Revert "CIV-13109: Added property for Set Aside Judgment Notification"

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
Reverts hmcts/civil-commons#132
> Revert "CIV-13171 Notify Judgment varied following Determination of Means"

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13134
Added template for Lip notification record judgment determination by means
```
[ ] Yes
[ ] No
```
> CIV-13134 add record judgment template

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
[CIV-13171- Email notifications: Claimant/Defendant LR - Judgment varied following Determination of Means](https://tools.hmcts.net/jira/browse/CIV-13171)
These notifications are generated following the editing of a Judgment by a caseworker after a determination of means
**Test of Email Notification:**
_Applicant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/b8e0cc53-8c8d-4be8-ac70-20cace8ce25a?from_statuses=sending,delivered,failed
_Defendant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/cea339f3-03c2-4897-9433-b1f9df33e010
_Applicant:_
https://www.notifications.service.gov.uk/services/a8b1617c-8e15-49aa-a8d3-a27a243f3c45/notification/e8ac41e0-22af-4df0-986c-3e63d4b1a0b3?from_sta …
> CIV-13171 Email notifications Judgment varied following Determination of Means

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13306
Set up Lip v Lip notifications properties
```
[ ] Yes
[x] No
```
> CIV-13306 Mediation notifications LiP vs LiP

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13306
Set Up Notification Properties
```
[ ] Yes
[x] No
```
> CIV-13306 Set Up Notification Properties

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-11698
```
[ ] Yes
[ ] No
```
> CIV-11698 Notify Claimant LiP Solicitor

- config/owasp/suppressions.xml
> CVE-0000 CVE Suppression

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13187
Set up notification properties for defendant notice of change
```
[ ] Yes
[x] No
```
> CIV-13187 Defendant NoC

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13312
cover the Welsh email notifications to be sent to the claimant LiP when the caseworker updates the case with mediation successful/unsuccessful.
```
[ ] Yes
[x] No
```
> CIV-13312 Mediation notifications Welsh

- src/main/java/uk/gov/hmcts/reform/civil/documentmanagement/model/DocumentType.java
https://tools.hmcts.net/jira/browse/CIV-13884
New document type for court officer order
```
[ ] Yes
[ x] No
```
> CIV-13884 New document type for court officer order

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13808
Set up mediation notification for the LR defendant in LR v Lip claim
```
[ ] Yes
[x] No
```
> CIV-13808 Mediation notifications LiP vs LR - defendant LR side

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13851
Evidence upload notification in Welsh
```
[ ] Yes
[x] No
```
> CIV-13851 - evidence upload notification

- src/main/java/uk/gov/hmcts/reform/civil/notify/NotificationsProperties.java
https://tools.hmcts.net/jira/browse/CIV-13856
Welsh template for HwF email
```
[ ] Yes
[x] No
```
> CIV-13856 - welsh template for help with fees LiP

- src/main/java/uk/gov/hmcts/reform/civil/service/UserService.java
- src/main/java/uk/gov/hmcts/reform/civil/utils/MaskHelper.java
- src/test/java/uk/gov/hmcts/reform/civil/service/UserServiceTest.java
https://tools.hmcts.net/jira/browse/DTSCCI-612
```
[ ] Yes
[ ] No
```
> DTSCCI-612 - Add try catch for potential sensitive info leak to mask email

- build.gradle
https://tools.hmcts.net/jira/browse/DTSCCI-856
Migrate from JCentre
```
[ ] Yes
[ ] No
```
> DTSCCI-856 Migrate from JCentre for civil-commons

- build.gradle
- lib/applicationinsights.json
https://tools.hmcts.net/jira/browse/DTSCCI-916
Reducing application insights by sampling health checks and minor CVE fix.
```
[ ] Yes
[ ] No
```
> DTSCCI-916 Reduce Application Insights

- src/main/java/uk/gov/hmcts/reform/civil/service/UserService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/UserServiceTest.java
> DTSCCI-1092 - feature toggled sys user logging

- build.gradle
- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/ras/client/RoleAssignmentsApi.java
- src/main/java/uk/gov/hmcts/reform/civil/ras/model/QueryRequest.java
- src/main/java/uk/gov/hmcts/reform/civil/ras/model/RoleAssignmentResponse.java
- src/main/java/uk/gov/hmcts/reform/civil/service/RoleAssignmentsService.java
- src/test/java/uk/gov/hmcts/reform/civil/service/RoleAssignmentsServiceTest.java
https://tools.hmcts.net/jira/browse/CIV-15377
- Added new role assignments query call/models and implemented retrieving role assignments, including labels, for a user in RoleAssignmentService.
```
[ ] Yes
[X] No
```
> CIV-15377 - CE - Role Assignments for Messages

- build.gradle
- config/owasp/suppressions.xml
- [ X] commit messages are meaningful and follow good commit message guidelines
- [ X] README and other documentation has been updated / added (if needed)
- [ X] tests have been updated / new tests has been added (if needed)
https://tools.hmcts.net/jira/browse/DTSCCI-1347
```
[ ] Yes
[ X] No
```
> Revisit Suppression Vulnerabilities - Civil Commons - CVE-2023-51775, CVE-2022-45688 and  CVE-2023-5072

- config/owasp/suppressions.xml
- src/main/java/uk/gov/hmcts/reform/civil/referencedata/model/LocationRefData.java
> CIV-16242 add Welsh name LocationRefData

- config/owasp/suppressions.xml
N/A
Suppress CVE-2024-38286
```
[ ] Yes
[x] No
```
> Suppress apache vuln

- src/main/java/uk/gov/hmcts/reform/civil/referencedata/model/LocationRefData.java
https://tools.hmcts.net/jira/browse/CIV-16671
Allow pulling of Welsh site name
```
[ ] Yes
[x] No
```
> CIV-16671 - Welsh Site name

- config/owasp/suppressions.xml
> DTSCCI-2086 cve suppression
